chore: Fix incorrect formatting
immich-app/CLI pull request #72
Opened 2023-03-20 12:07 UTC by etnoy

In a previous PR of mine I submitted code without having the vscode environment set up properly, sorry! This meant the code was incorrectly formatted.

This PR fixes this issue and also adds the .vscode folder to gitignore

2023-03-23 15:12 UTC, jrasm91 requested changes
This reverts my last change which fixed a bug with large file scans.

We should add a `.prettierrc` file (copied from immich repo server/ folder). The changes should _only_ be formatting. It looks like you need to rebase the branch before doing the formatting.

2023-03-23 15:12 UTC, jrasm91 commented on bin/index.ts
> +        ...((await crawler.crawl(newPath).withPromise()) as PathsOutput)
This doesn't work for large lists of files.

2023-03-23 15:33 UTC, jrasm91 approved these changes

2023-03-24 10:22 UTC, etnoy commented on bin/index.ts
> +        ...((await crawler.crawl(newPath).withPromise()) as PathsOutput)
Done thanks to your fix

2023-03-25 01:46 UTC, merged